apiVersion: apps/v1
kind: Deployment
metadata:
  name: netwatch
  labels:
    app: netwatch
spec:
  replicas: 2
  selector:
    matchLabels:
      app: netwatch
  template:
    metadata:
      labels:
        app: netwatch
    spec:
      containers:
        - name: netwatch
          image: ghcr.io/mustaphahandag/netwatch:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: netwatch-db-secret
                  key: db-url
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: netwatch-db-secret
                  key: db-user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: netwatch-db-secret
                  key: db-password
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 20
